### PR TITLE
Add explorer link to Help menu

### LINKED ISSUE #282: Explorer links
Maybe it would make sense to display links to testnet explorer and mainnet explorer inthe Help dropdown menu.

### PR DESCRIPTION
**Pull request by alepop**
Open test explorer or main based on the network. 
Close #282

### CODE REVIEW

**Comment by reyraa** [comment]
Thank for the good job Aleksey.
I'd like to bring up to points about this PR:
 - Since we have links to Lisk website, forum and chat under help item in system menu, I think that' the right place also for the link to Lisk explorer.
 - Since we have a list of transactions, would be great if we have your current logic under a directive that we can use by clicking the transaction id opening explorer.

**Comment by alepop** [comment]
@reyraa ok. I will update branch based on your comment

**Comment by alepop** [comment]
@reyraa can i implement all 2 feature in this PR, or I need to create new for `open transaction in explorer`?

**Comment by alepop** [comment]
Simply add Lisk explorer link to the Help menu

**Comment by reyraa** [comment]
@alepop  I think this suits current needs better. Thanks

**Review by reyraa — APPROVED** [review]

**Pull request merged**
