### PR TITLE
Make files organisation clearer - Closes #154

### LINKED ISSUE #154: Make files organisation clearer
### Expected behaviour
Some files should be moved and/or renamed, namely:
```
# adhere to cammelCase
mv src/app/lisk-nano.js src/app/liskNano.js
mv src/app/services/sign-verify.js src/app/services/signVerify.js
mv src/app/components/sign-verify/sign-message.js src/app/components/sign-verify/signMessage.js 
mv src/app/components/sign-verify/sign-message.pug src/app/components/sign-verify/signMessage.pug 
mv src/app/components/sign-verify/verify-message.js src/app/components/verify-verify/verifyMessage.js 
mv src/app/components/sign-verify/verify-message.pug src/app/components/verify-verify/verifyMessage.pug
mv src/app/components/sign-verify/ src/app/components/signVerify/

# this one need to be merged with ./package.json
mv src/package.json ./

# make folder structure cleaner
mv src/app/services/peers/peers.js src/app/services/
rmdir src/app/services/peers/
mv src/app/* src/
rmdir src/app
mv src/test ./test
mv src/spec ./e2e-test

# move conf files to root
mv src/webpack.config.babel.js ./
mv src/karma.conf.js ./
mv src/.eslintrc.json ./
```

Consequently, all the files that refer to the aforementioned have to be updated.
Also, unit test files cammelCase should be updated accordingly.

### Actual behaviour
All files are in their current location

### PR DESCRIPTION
**Pull request by alepop**
Resolve #154 
- [x] make file camelCased
- [x] merge package.json
- [x] move conf to root
- [x] add missed eslint package to project

### CODE REVIEW

**Comment by alepop** [comment]
@Isabello maybe I do something wrong in Jenkins config file?

**Comment by slaweet** [comment]
@alepop there were some changes to Jenkinsfile, so now there are two more occurrences of `cd $WORKSPACE/src` that need to be fixed

**Comment by alepop** [comment]
@slaweet I am already removed `/src` path from jenkins config.

**Comment by Isabello** [comment]
Please update your branch from development. The wrong resource was being locked causing concurrent builds to be blown away in the middle. This is now fixed.

**Review by slaweet — APPROVED** [review]

**Pull request merged**
