### PR TITLE
Fix infinity scroll - Closes #623

### LINKED ISSUE #623: Infinite scroll loading should start earlier than when the bottom is hit
### Expected behaviour
Infinite scroll loading should start earlier than when the bottom is hit (~1 screen height earlier).
It worked like that before React migration and felt more smooth.
### Actual behaviour
Infinite scroll loading starts when bottom of the page is hit
### Steps to reproduce
- Open Nano
- Login
- Go to "delegates"
- scroll

### PR DESCRIPTION
**Pull request by alepop**
closes #623

### CODE REVIEW

**Review by slaweet — CHANGES_REQUESTED** [review]
Thanks for the PR, it's a good start.
I can see two issues:
- the infinite scroll in transactionsComponent.js doesn't work. It's because of recent refactoring, not because of this PR, but it makes sense to fix it here. The problem is not setting `this.canLoadMore = true` after the request is finished.
- The scrolling still doesn't feel smooth - I'm often waiting on the end of the list for the finish of loading. Sometimes I even had to scroll back a little to load more. Tested on mainnet list of delegates.

**Comment by reyraa** [comment]
Please consider adding `scrollableAncestor` to make sure the scroll event listener is bound to window:
```
<Waypoint
          scrollableAncestor={window}
          onEnter={this.loadMore.bind(this)}>
</Waypoint>
```
this will solve the issue.

**Comment by alepop** [comment]
@reyraa thanx 👍

**Comment by slaweet** [comment]
It still doesn't load more transactions with some screen heights. For example, I was running with `1343px`. I think that the problem is that the waypoint is so high that it is unable to reach the bottom.

**Comment by slaweet** [comment]
Now it works good, just this one e2e test needs to be updated:
```
Failures:

1) Scenario: should show transactions - features/transactions.feature:2
   Step: Then I should see table with 20 lines - features/transactions.feature:5
   Step Definition: features/step_definitions/generic.step.js:74
   Message:
     AssertionError
         + expected - actual

         -40
         +20
```
https://jenkins.lisk.io/job/lisk-nano/job/PR-643/4/console

**Review by slaweet — APPROVED** [review]

**Pull request merged**
